name: Beyond Transparency
markdown: rdiscount
highlighter: true
# pygments: true
# 'pygments' renamed to 'highlighter'
# relative_permalinks: true
# Relative Permalink support removedPermalink
# https://jekyllrb.com/docs/upgrading/2-to-3/
